### ISSUE TITLE
Queastions about training with AE

### ISSUE THREAD

**Issue by zugofn** [claudemircasa/hptiny#3]
Hi,Sir!
Thanks for your great work!
I'm very interesting in your work with AE(Assisted Excitation) model!
Could you release your training code?I want to know how you use AE to train you model!
Thank you so much!
Have a good day!
😊

**Comment by claudemircasa** [comment]
@zugofn, basically I do the training normally and convert the final model to ONNX, after the conversion I didn't use Darknet anymore, only ONNX. In my article are the positions of the AE layers (https://www.brazilianjournals.com/index.php/BRJD/article/view/24580).
I used the @AlexeyAB implementation, try the following thread, you will find the implementation details for this type of layer.

https://github.com/AlexeyAB/darknet/issues/3417

**Comment by zugofn** [comment]
> @zugofn, basically I do the training normally and convert the final model to ONNX, after the conversion I didn't use Darknet anymore, only ONNX. In my article are the positions of the AE layers (https://www.brazilianjournals.com/index.php/BRJD/article/view/24580).
> I used the @AlexeyAB implementation, try the following thread, you will find the implementation details for this type of layer.
> 
> [AlexeyAB/darknet#3417](https://github.com/AlexeyAB/darknet/issues/3417)

wow!Thanks for your detailed reply,bro! I will study the content of your links.
best wishes!
